name: Generate Pac-Man contribution graph

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows you to manually trigger it at any time
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: pencilrebel/pacman-contribution-graph@master
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}
          # The branch where the animated SVG will be pushed
          output_branch: output